# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '3.4'

services:
  app:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    networks:
      - lan
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA}:/home/step
    hostname: ${APP_SITE}
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.tcp.routers.${APP_TAG}.rule=HostSNI(`${APP_SITE:?Must be set}`)
      - traefik.tcp.routers.${APP_TAG}.tls.passthrough=true
      - traefik.tcp.routers.${APP_TAG}.service=${APP_TAG}
      - traefik.tcp.services.${APP_TAG}.loadbalancer.server.port=9000
    environment:
      - DOCKER_STEPCA_INIT_NAME=Dcape
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,${APP_SITE}
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_SSH=true
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_PASSWORD=${ADMIN_PASSWORD}
      - PGSSLMODE=disable
      - PGHOST=db
      - PGDATABASE
      - PGUSER
      - PGPASSWORD

networks:
  lan:
    name: ${DCAPE_NET}
    external: true

