# app custom Makefile


# Docker repo & image name without version
IMAGE    ?= smallstep/step-ca

# Hostname for external access
APP_SITE ?= stepca.dev.lan

# App names (db/user name etc)
APP_NAME ?= stepca

# PgSQL used as DB
#USE_DB = yes

ADMIN_PASSWORD       ?= $(shell openssl rand -hex 16; echo)

# ------------------------------------------------------------------------------
# app custom config

IMAGE_VER            ?= latest

APP_HOST ?= $(shell hostname -f)

DCAPE_ROOT           ?= /opt/dcape/var

DATA_PATH            ?= $(APP_NAME)

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

ADMIN_PASSWORD=$(ADMIN_PASSWORD)

APP_HOST=$(APP_HOST)

# Path to /opt/dcape/var. Used only outside drone
DCAPE_ROOT=$(DCAPE_ROOT)

DATA_PATH=$(DATA_PATH)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif
